services:
  sleipnir:
    image: eqalpha/keydb
    container_name: sleipnir
    restart: always
    volumes:
      - ./data/sleipnir:/data
    ports:
      - 6379:6379
    networks:
      - hestia

networks:
  hestia:
    driver: bridge